//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAntonIncidents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleCallFlow
    {
        public int ID { get; set; }
        public  int Action { get; set; }
        public decimal Section { get; set; }
        public string Verbage { get; set; }
        public string Sectiontype { get; set; }
        public string QuestionType { get; set; }
        public int PrimarySection { get; set; }
        public int SubSection { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
